export const categoryList = [
  { name: "Food" },
  { name: "Snacks" },
  { name: "Vegetables" },
  { name: "Fruits" },
  { name: "Flowers" },
  { name: "Travel" },
  { name: "Swamy" },
  { name: "Rent" },
  { name: "Maintenance" },
  { name: "Grocery" },
  { name: "Gas" },
  { name: "Electricity" },
  { name: "Communication" },
  { name: "Internet" },
  { name: "Fuel" },
  { name: "Medicals" },
  { name: "Gym" },
  { name: "Shopping" },
  { name: "Clothing" },
  { name: "Entertainment" },
  { name: "Festivals" },
  { name: "Gift" },
  { name: "Investments" },
  { name: "Insurance" },
  { name: "Credit Card" },
  { name: "Loan" },
  { name: "Others" },
  { name: "Transfer" },
  { name: "Salary" },
];

export const categoryColors = [
  { category: "Food", budget: 0, color: '#FF5733' },
  { category: "Vegetables", budget: 0, color: '#AAD0F0' },
  { category: "Fruits", budget: 0, color: '#5A20A1' },
  { category: "Flowers", budget: 0, color: '#11FFA0' },
  { category: "Snacks", budget: 0, color: '#42A5F5' },
  { category: "Travel", budget: 0, color: '#FFD700' },
  { category: "Swamy", budget: 0, color: '#4CAF50' },
  { category: "Rent", budget: 0, color: '#FF4081' },
  { category: "Maintenance", budget: 0, color: '#009688' },
  { category: "Grocery", budget: 0, color: '#E91E63' },
  { category: "Gas", budget: 0, color: '#FF5722' },
  { category: "Electricity", budget: 0, color: '#673AB7' },
  { category: "Communication", budget: 0, color: '#FFC107' },
  { category: "Internet", budget: 0, color: '#1E90FF' },
  { category: "Fuel", budget: 0, color: '#FFA07A' },
  { category: "Medicals", budget: 0, color: '#008080' },
  { category: "Gym", budget: 0, color: '#9932CC' },
  { category: "Shopping", budget: 0, color: '#F0E68C' },
  { category: "Clothing", budget: 0, color: '#FF69B4' },
  { category: "Entertainment", budget: 0, color: '#00FF7F' },
  { category: "Festivals", budget: 0, color: '#ADFF2F' },
  { category: "Gift", budget: 0, color: '#2DBF2A' },
  { category: "Investments", budget: 0, color: '#D2691E' },
  { category: "Insurance", budget: 0, color: '#7B68EE' },
  { category: "Credit Card", budget: 0, color: '#E9967A' },
  { category: "Loan", budget: 0, color: '#7FFF00' },
  { category: "Others", budget: 0, color: '#B22222' },
  { category: "Transfer", budget: 0, color: '#4682B4' },
  { category: "Salary", budget: 0, color: '#BA55D3' },
];
